# Site
name: 'Evocation.no'
description: 'Min digitale hippocampus'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/mundana-theme-jekyll'

email: 'ptmadsjorgensen@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Mads
      site:           https://www.wowthemes.net
      avatar:         /assets/images/mads1.jpg
      bio:            "Hei, jeg heter Mads og er eieren av denne nettsiden. I disse dager tar jeg en Master i psykologi ved Universitetet i Oslo, og hvor jeg tenkte å bruke denne siden som er forlengelse av min egen hukommelse."
      email:          ptmadsjorgensen@gmail.com
      twitter:        https://twitter.com/madsfjorgensen
    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
    
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]