# Site
name: 'Psykoblogg'
description: 'Et sted for de som har interesse for temaer innen psykologi.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/mundana-theme-jekyll'
disqus: 'demowebsite'
email: 'ptmadsjorgensen@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    mads:
      name:           Mads E. Falch Jørgensen
      site:           https://madsjorgensen.no
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hei, jeg heter Mads og har en Bachelor i anvendt psykologi, og drømmer om en master i Psykologi med fokus på helse, utviklig og kultur. I tillegg er jeg medeier av et PT-studio hvor jeg til daglig jobber som personlig trener"
      email:          ptmadsjorgensen@gmail.com
      twitter:        https://twitter.com/madsefjørgensen

    andrine:
      name:           Andrine Eileen Støver
      site:           https://andrineeileen.no
      avatar:         /assets/images/avatar2.jpg
      bio:            "Personlig trener og en jevnt over veldig fornuftig person!"
      email:          ptandrine@gmail.com
      Instagram:        https://instagram.com/andrineeileen
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]